

# Mouse support
set -g mouse on

# Instant escape response time (prevents query buffer leaks)
set -s escape-time 0

# Disable passthrough and color queries from rxvt
#set -g allow-passthrough off
#set -as terminal-features ',rxvt*:noosctitle:bcolor@'
#set -as terminal-overrides ',rxvt*:XT@:Ms@:Cc@:Cr@:Cs@:Csr@'

# Status bar position and base colors
set -g status-position top
set -g status-style bg=default,fg=default

# Clear left side and window list completely
set -g status-left ""
set -g window-status-format ""
set -g window-status-current-format ""

# Fixed right side text
set -g status-right "v Λ x"

# Remove copy-mode line counter and background highlight
set-window-option -g mode-style bg=default,fg=default
